#!/bin/sh

PYR_PID_FILE=/tmp/rnotify.$DISPLAY
ASSH_PID_FILE=/tmp/rnotify.autossh.$DISPLAY
LPORT=4321
RPORT=4321

function stop {
    if [ -e $2 ]; then
        kill -15 `cat $2`
        if [ ! $? ]; then
            echo "Could not terminate process, try fire!"
            kill -9 `cat $2`
        fi
        rm -f $2
        echo "Stopped ${1}"
    fi
}

if [ "$1" == "stop" ]; then
    if [ "$2" == "autossh" ]; then
        stop "autossh" $ASSH_PID_FILE
    else
        if [ "$2" == "all" ]; then
            stop "autossh" $ASSH_PID_FILE
        fi
        stop "pyrnotify" $PYR_PID_FILE
    fi
fi

if [ "$1" == "start" ]; then
    stop "pyrnotify" $PYR_PID_FILE
    python2 ~/.dwm/pyrnotify.py $LPORT &
    echo $! > $PYR_PID_FILE
    echo "Started pyrnotify on port $LPORT"
    
    if [ "$2" == "autossh" ]; then
        stop "autossh" $ASSH_PID_FILE
        autossh -M0 -q -N -o "ServerAliveInterval 60" -o "serverAliveCountMax 3" -R ${LPORT}:localhost:${RPORT} cui.kofish.org &
        echo $! > $ASSH_PID_FILE
        echo "Started autossh on $LPORT : $RPORT"
    fi
fi


#(if [ -n `ps aux | grep '[r]notify'` ]; then
#   kill -9 `ps aux | grep '[r]notify' | awk '{print $2}'`
# fi
# python2 ~/.dwm/rnotify-client.py 4321 &
# exec autossh -M0 -q -f -N -o "ServerAliveInterval 60" -o "ServerAliveCountMax 3" -R 4321:localhost:4321 cui.kofish.org & ) &

