#!/bin/sh

if [ $1 == "on" ]; then
    echo "Turn to tv!"
    xrandr --output DVI-I-1 --off
    xrandr --output TV-0 --auto
    vlc &
    sleep 5s
    xdotool search --classname "vlc" windowmove 25 73 windowsize 970 652
else if [ $1 == "off" ]; then
    echo "Turn on secondary monitor instead!"
    xrandr --output TV-0 --off
    xrandr --output DVI-I-1 --auto --right-of VGA-0
fi
fi
