#!/bin/bash

DWM_LOG="${HOME}/.dwm/dwm.${DISPLAY:1}.log"

# xcompmgr -CfFD3 &

#switch /usr/share/themes/Smooth-Tangerine-Dream &

# while true; do
# 	# xsetroot -name "`yaourt -Qu --aur | wc -l` packages | `date +"%F %R"`"
# 	xsetroot -name "`date +"%F %H:%M:%S"`"
# 	sleep 2s
# done &

# (sleep 3s
#   killall notification-daemon &> /dev/null
#   statnot &
# ) &

#( sleep 5s
 #keynav || notify-send "Keynav failed" "Something happened and keynav crashed" ) &


 ( sleep 20s && exec $HOME/.dwm/dzenconky.sh & )
 ( sleep 20s && exec parcellite & )
 ( sleep 20s && exec $HOME/.dwm/background_switcher.sh & )
 ( sleep 20s && exec $HOME/.dwm/compton & )
 ( sleep 20s && exec redshift -c $HOME/.config/redshift.conf & ) &
 #( exec $HOME/.bin/rnotification start autossh & ) &

exec /usr/bin/dwm $@ >> ${DWM_LOG} 2>&1 
